Parameters:
  BucketNamePrefix:
    Description: The bucket name prefix used for testing
    Type: String

Resources:

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ['-', [!Ref BucketNamePrefix, !Ref 'AWS::Region']]
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Bucket:
    Description: Bucket ARN
    Value: !GetAtt Bucket.Arn
